mattupstate/flask-security

- AUTHORS
- docs/configuration.rst
- flask_security/core.py
Add the ability to set token expiration by configuring the SECURITY_TOKEN_MAX_AGE value.
> Add configuration for token expiration

- flask_security/datastore.py
get_user(identifier) checks if the identifier is a number by trying to convert it to int. This works for strings, but in a particular case, when identifier is None, it fails. Checking for both TypeError and ValueError fixes it.
> Fail silently for get_user(None)

- .gitignore
- docs/configuration.rst
- flask_security/utils.py
- tests/test_trackable.py
We should be using whatever the last IP in `X-Forwarded-For` is. Note that in order for this to work properly behind a trusted proxy (i.e. if you are using nginx / similar to forward to `gunicorn` / similar, as is common), you must use `ProxyFix` as described in the `werkzeug` and `flask` documentation. I've added a note to the docs for `SECURITY_TRACKABLE` to point that out, since it's probably not obvious. Perhaps a note should be added elsewhere too? Not sure.
From the nginx docs: http://nginx.org/en/docs/http/ngx_http_proxy_module.html
```
$proxy_add_x_forwarded_for
the “X-Forwarded-For” client request header field with the $remote_addr variable
appended to it, separated by a comma. If the “X-Forwarded-For” field is not present
in the client request header, the …
```
> X-Forwarded-For can contain multiple IP addresses

- flask_security/decorators.py
- tests/test_common.py
When using @http_auth_required, the WWW-Authenticate header is included, but when using @auth_required('basic'), it is not.
This change includes that header in every @auth_required call that contains the 'basic' method.
> Include WWW-Authenticate headers in @auth_required.

- flask_security/core.py
- flask_security/decorators.py
- tests/test_misc.py
Right now, when using `@http_auth_required` or `@auth_token_required`, if the user is unauthorized only a message is returned (`_default_unauthorized_html`).
With this change, it is possible to define an unauthorized callback which will be called instead.
Example using your overholt project (`overholt/api/__init__.py`):
```python
from overholt.core import security
def unauthorized():
return jsonify(dict(error='Unauthorized')), 403
def create_app(settings_override=None, register_security_blueprint=False):
app = factory.create_app(__name__, __path__, settings_override,
register_security_blueprint=register_security_blueprint)
security.unauthorized_handler(unauthorized)
```
I have tested it only with `@http_auth_required`, but `@auth_required` and `@auth_token_required` should work pretty …
> Allow overriding of an unauthorized callback.

- docs/configuration.rst
- requirements-dev.txt
As of 2.0.0, passlib no longer correctly identifies bcrypt as bcrypt
(instead, it mistakenly applies pybcrypt logic to bcrypt). This results
in all Python 3 logic involving bcrypt failing. As a hotfix, we should
require users to be on a version of bcrypt that passlib can handle a fix
can be pushed into passlib.
> Restrict bcrypt to <2.0.0

- .travis.yml
- requirements-dev.txt
- setup.py
- tox.ini
- Add Python 3.5 support on travis
- pytest-cache has been merged into pytest [0] and is no longer
separately maintained, so pytest-cache-related requirements are being
updated.
- Flask-Mongoengine latest stable is broken on Python 2.6 (but fixed in
master [1]), so its version is being restricted for now.
[0] http://pytest.org/latest/changelog.html#id3
[1] https://github.com/MongoEngine/flask-mongoengine/pull/174
> Fix tests, add py35

- .travis.yml
- docs/configuration.rst
- requirements-dev.txt
- requirements.txt
Due to a bug in passlib [0], use of bcrypt>=0.2.0 was not working
properly. As of passlib==1.6.4, that bug is fixed [1]. The minimum
required version of passlib is upgraded to 1.6.4 to address this issue
and properly support current versions of bcrypt. Because pypy is
outdated on travis [2,3], a fix [4] to bring it up to date is needed
(locally, tests pass with pypy >= 2.6 but not 2.5, the current version
used on travis).
[0] https://bitbucket.org/ecollins/passlib/issues/56
[1] https://bitbucket.org/ecollins/passlib/src/fa26802fc88fbc6b2d4b9676970bed7e6d53fc9d/CHANGES?at=default&fileviewer=file-view-default#CHANGES-130,131
[2] https://github.com/travis-ci/travis-ci/issues/4756
[3] https://github.com/travis-ci/travis-ci/issues/5027
[4] …
> Upgrade passlib, remove bcrypt restriction

- docs/configuration.rst
> Fix missing `SECURITY_SUBDOMAIN` in config docs

- flask_security/forms.py
Removed from `_default_field_labels` (forms.py) a duplicate definition of `'retype_password': 'Retype Password'` (left in line 36)
> Remove a duplicate line 

- docs/quickstart.rst
In the most recent versions of flask, importing `flask.ext.*` will result in a warning message. The preferred way to import is `flask_*`. This PR updates the quickstart documentation to reflect this change.
> Use new style flask imports

- flask_security/datastore.py
Make sure `PeeweeUserDatastore.delete_user()` also deletes related `UserRoles` records.
It's a potential vulnerability (a future user might gain unintended roles if the id is reused), and the delete might even fail if `User` has other constraints (e.g. a profile record).
> Cascade PeeweeDatastore delete

- flask_security/forms.py
- requirements.txt
We just began seeing all these warnings in our project:
```
/Users/jacquerie/.virtualenvs/inspire/lib/python2.7/site-packages/flask_security/forms.py:89: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
class Form(BaseForm):
/Users/jacquerie/.virtualenvs/inspire/lib/python2.7/site-packages/flask_security/forms.py:154: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
class SendConfirmationForm(Form, UserEmailFormMixin):
/Users/jacquerie/.virtualenvs/inspire/lib/python2.7/site-packages/flask_security/forms.py:173: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
class ForgotPasswordForm(Form, UserEmailFormMixin): …
```
> Bump Flask-WTF to 0.13

- AUTHORS
- flask_security/utils.py
- tests/test_trackable.py
Changes trackable behavior of `login_user` when IP can not be detected
from a request from 'untrackable' to `None` value.  (closes #448)
> utils: use `None` instead of 'untrackable' for IPs

- flask_security/core.py
- flask_security/decorators.py
- requirements.txt
- tests/test_common.py
Just moved some code around, but the main change is using `request_loader` on the login manager instead of `token_loader` to fix #557.
> replace token loader with request loader to fix #81

- flask_security/confirmable.py
- tests/test_confirmable.py
When validating a confirmation token, also checks if the email that
the token was created with matches the user's current email.
> security fix for changed email confirmation

- flask_security/utils.py
- tests/test_trackable.py
When `SECURITY_TRACKABLE` is enabled, one must commit the transaction after the request in which `login_user` is called. This is used throughout `flask_security` and was learned from reading the code.
This also adds a test which shows how this works.
> Add notes to documentation for login_user. Closes #566.

- docs/configuration.rst
- flask_security/confirmable.py
- flask_security/core.py
- flask_security/utils.py
- tests/conftest.py
Added new configuration option `SECURITY_TIMEZONE_AWARENESS` which can
be used to force default timezone.
(closes mattupstate/flask-security#466)
(cc @philsalesses)
> Configurable timezone aware datetimes

- AUTHORS
- flask_security/confirmable.py
- flask_security/core.py
- flask_security/recoverable.py
- flask_security/utils.py
- tests/test_misc.py
Use sha512 instead of md5 for any hashing operation. MD5 is completely broken and should not be used for anything related to password. Even using MD5 to share password hashes should be treated as if giving the hashes in plaintext.
> Replace md5 hashing with sha512

- docs/features.rst
- docs/index.rst
The links to Flask-Login were outdated in the documentation.
> fixed Flask-Login link in docs

- flask_security/utils.py
I'm getting this exception when registering a user (after upgrading to latest master of Flask-Security-Fork, that includes fully localized messages):
127.0.0.1 - - [06/May/2017 08:44:01] "POST /register/ HTTP/1.1" 500 -
Traceback (most recent call last):
File "/home/jaza/wsgi/archiunit/env/lib/python3.5/site-packages/flask/app.py", line 2000, in __call__
return self.wsgi_app(environ, start_response)
File "/home/jaza/wsgi/archiunit/env/lib/python3.5/site-packages/flask/app.py", line 1991, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/home/jaza/wsgi/archiunit/env/lib/python3.5/site-packages/flask/app.py", line 1567, in handle_exception
reraise(exc_type, exc_value, tb)
File "/home/jaza/wsgi/archiunit/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in …
> Use gettext instead of lazy_gettext so Flask's flash doesn't error

- docs/models.rst
- flask_security/core.py
- flask_security/views.py
Sometimes after Create or Login an user (base on Token) we need some information about he/she, so after receive the token we need to request again the server.
Example: 
When we send the email and password Flask-Security returns:
```python
{
"meta": {
"code": 200
},
"response": {
"user": {
"authentication_token": "WyI5OTk5OTk5IiwiMTE0ODZlNzU3MGNjNWRkMjFiZDhkMzI4M2I5ZTUxZjYiXQ.C39mEg.UGm6QqOaGlZ3wJsu5jQuWaIIA8M",
"id": "9999999"
}
}
}
```
Is really good. But if we need more information we should request the server again.
I introduced a new setting flag called SECURITY_CUSTOM_USER_PAYLOAD. By default is False.
If you set to True, you must define a function in your User Model called 'payload_handler' that must return a serializable object:
```python
UserModel(Base, UserMixin):
id = …
```
> Custom User Payload Handler

- flask_security/forms.py
Data required validators are added to several fields since these fields are always essencial. Then invalid requests with empty fields won't hit server side and website users should have better experiences.
- Data required valildators are added to ```email``` and ```password``` fields of ```LoginForm``` since they are always needed for login.
-  Data required valildators are added to ```new_password_confirm``` and ```password_confirm``` in ```ChangePasswordForm``` and ```PasswordConfirmFormMixin``` respectively since reconfirmed password are also always neccessary.
> Add validators to default LoginForm

- flask_security/core.py
- flask_security/utils.py
Defines `localize_callback` proxy to I18N domain stored in the extension
state object.  (closes #621)
> core: set localize_callback for login manager

- flask_security/forms.py
- tests/test_changeable.py
**Problem**
In the password change form (`flask_security.forms.ChangePasswordForm`), `strip()` is used to compare old and new passwords. However, whitespace is an accepted part of a password (as long as it's accompanied by other characters). For example, '     a' (six leading spaces) and 'a     ' (six trailing spaces) are two different and both *valid* passwords. Indeed, Flask-Security allows for both as valid passwords to be used, and they are not interchangeable on login. However, because the `strip()` is currently being done, on the password change form, you incorrectly get the message that the two distinct passwords are the same.
**Solution**
`strip()` is no longer used to compare if an old password and a new password are the same.
**Miscellanea**
As for the philosophical argument of …
> Do not use strip() to compare passwords in flask_security.forms.ChangePasswordForm

- docs/configuration.rst
- flask_security/utils.py
- tests/test_hashing.py
Allows the usage of a variable number of rounds when using bcrypt. Set
the rounds to 4 in test_hashing.py, and add a test for an invalid number of
rounds (e.g. 3).
#426
> Add support for a SECURITY_BCRYPT_ROUNDS setting.

- flask_security/forms.py
- flask_security/translations/fr_FR/LC_MESSAGES/flask_security.po
A French translation for `flask_security`, sponsored by https://github.com/etalab.
It would be great if this could be included in the (much anticipated) next release!
Have a good day.
> French translation

- flask_security/cli.py
- flask_security/script.py
The keyarg `csrf_enabled` is deprecated in `flask-wtf`. This PR switches to `meta={'csrf': False}` as advised here: https://github.com/lepture/flask-wtf/blob/master/flask_wtf/form.py#L81
> `csrf_enabled` deprecation fix

- flask_security/decorators.py
- tests/test_common.py
_get_unauthorized_view() is blindly trying to redirect to the referrer,
without checking if we came from there in the first place. This change
avoids the loops that result from that, by redirecting to `/` if we just
came from the referrer.
A unit test is also provided.
Without this change, the end result is that the browser enters into a
redirect loop, until eventually it goes to the correct place (I haven't
figured out how many; in production we've seen 10s, but in the provided
unit test it only happened 3 times). It also results in multiple
flash messages being printed once the final page is loaded.
Fixes #670
> Fix referrer loop in _get_unauthorized_view().

- flask_security/datastore.py
`Datastore.find_user()` is used on every page load to verify the user in
the current session; until now, `find_user()` would trigger 2+ DB
accesses, since the `roles` relationship uses lazy loading by default.
This is useful to reduce the rows accessed when retrieving multiple
users from the DB.
However, in `find_user()` we always retrieve only one, so
it makes sense to retrieve all roles in one SQL operation instead of
always triggering 2 or more.
This would be unnecessary if the `roles` relationship was defined with
`lazy="joined"`. However, that would greatly increase the number of rows
accessed on all queries (even when querying all users), so I think it's
better to be selective and optimize only these accesses which happen on
every page load.
> Optimize DB accesses by using an SQL JOIN when retrieving a user.

- flask_security/core.py
If data is a py `list` we change it to a empty `dict`. So that the get attribute is available. 
https://github.com/mattupstate/flask-security/issues/681
> fix issue #681

- flask_security/forms.py
As detailed in #357 the time it takes to process a login request is
considerably less if the user specified doesn't exist than if the
password is incorrect. This can be used as a user enumeration attack,
even if the login error messages were customized to avoid this.
I fixed it by increasing the response time of a non-existing user
request by hashing the given password anyway (if using good
password hashing algorithm this is what takes a relatively
large amount of time and makes the attack possibly)
Without the fix:
```bash
$ time curl 'http://localhost:5000/login' --data 'next=&email=not%40existing.com&password=12312312312&next=&submit=Login' -s> /dev/null
curl 'http://localhost:5000/login' --data  -s > /dev/null  0,02s user 0,00s system 43% cpu 0,037 total
$ time curl …
```
> Fix timing attack on login form

- flask_security/translations/de_DE/LC_MESSAGES/flask_security.po
Translate all occurrences of "instructions" with "Anleitung" instead of "Instruktionen" to sound less technical;
translate "account" with "Konto" consistently;
translate "login" was translated with "anmelden" or "Anmledung" consistently;
Connect "E-Mail-Adresse" with dashes.
> Improve German translation

- flask_security/translations/es_ES/LC_MESSAGES/flask_security.po
A Spanish translation for `flask_security`, sponsored by https://github.com/etalab.
cc @odtvince @abulte @noirbizarre
> Spanish translation

- flask_security/utils.py
This PR use `Security.render_template` in mails too (allow custom `render_template` function, mostly for theming support)
> Use Security.render_template in mails too

- docs/quickstart.rst
Details:
* Fix exception raised when 'SECURITY_PASSWORD_SALT' is not set, as 'SECURITY_PASSWORD_HASH' [bcrypt] requires it which is default.
* render method is not found, replaced the same with render_template_string.
* render_template_string is utilised to show an example of usage of current user retaining the previous use case.
> Documentation/Quickstart: Fix SQLAlchemy app example for missing render method and adding salt

- docs/quickstart.rst
The current version is not formatting the code blocks as it should, it is shown as normal text: https://flask-security.readthedocs.io/en/latest/quickstart.html#id2
> Fix formatting for Basic SQLAlchemy section

- flask_security/core.py
Similar to [PR #366 ](https://github.com/mattupstate/flask-security/pull/366) fixed _request_loader to be able to receive arbitrary jsons (not only dict). Currently if json is not dict server sends 500
> Fix AttributeError in _request_loader

- flask_security/utils.py
* Fixes error when sending emails using Flask-Mail, without setting the
SECURITY_EMAIL_SENDER (closes #685).
> utils: fix incorrect email sender type

- docs/configuration.rst
- flask_security/core.py
- flask_security/utils.py
- tests/test_hashing.py
This PR makes `SECURITY_PASSWORD_SINGLE_HASH` a list of password hashing schemes that shouldn't be hashed twice allowing easier handling of legacy schemes or imported schemes.
- I want to import my Django passwords in my Flask-Security based app and have `bcrypt` with double hashing as default scheme, but Django only perform single hashing. (handled in default configuration)
- I add Flask-Security to default on `pbkdf2_sha256` hashed once but I want to migrate to `bcrypt` hashed twice without loosing already stored passewords. This can be handled with:
```python
'SECURITY_PASSWORD_HASH': 'bcrypt',
'SECURITY_PASSWORD_SALT': 'any string',
'SECURITY_PASSWORD_SINGLE_HASH': ['pbkdf2_sha256'],
'SECURITY_PASSWORD_SCHEMES': ['bcrypt', 'pbkdf2_sha256']
```
This ensure backward compatibility with …
> Make SECURITY_PASSWORD_SINGLE_HASH a list of scheme ignoring double hash

- flask_security/core.py
- tests/test_datastore.py
Currently, this extension cannot be used with the factory pattern, except by subclassing `Security` to override the `__init__` and `init_app` methods. The problem is two-fold: `kwargs` passed to `__init__` don't get passed on to `init_app`, and secondly, when setting the `datastore` via `__init__`, when `init_app(app)` is later called, it wipes out the `datastore`. This PR replaces #495, which appears to have stalled.
The datastore bug was introduced in #537, and was warned about by @mattupstate in a [comment](https://github.com/mattupstate/flask-security/pull/537#issuecomment-272888626), but that PR got accidentally merged anyway.
The following is currently the only method of initializing the extension:
```python
app = Flask(__name__)
datastore = SQLAlchemyUserDatastore(db, User, Role) …
```
> bugfix: support application factory pattern
