mattupstate/flask-security

docs/features.rst

Per http://english.stackexchange.com/questions/75786/overrode-vs-overridden

"overrided" --> "overriden"

---

.gitignore
flask_security/recoverable.py
flask_security/utils.py
tests/test_recoverable.py

Like https://github.com/mattupstate/flask-security/pull/382 but with tests.

Reset Password Fixes

---

.travis.yml

Migrate to Travis container-based infrastructure.
Advantages are listed here:
http://docs.travis-ci.com/user/migrating-from-legacy

Migrate to Travis container-based infrastructure, optimize build with pip caching.

---

flask_security/utils.py
flask_security/views.py

Added support for lazy post logout view configuration

---

flask_security/views.py

Fix login view to fill with request form data

Fix login view filling

---

flask_security/__init__.py
flask_security/datastore.py
tests/conftest.py

An extension and update of #359 
Added *basic* pony orm support and made the tests pass. I have started to use this in production, so I'll push through any additional errors if I find them.

Pony ORM Support

---

docs/customizing.rst

#194 
@jirikuncar I did't attach the ```flask_mail.Message``` can not be jsonified part since that looks like more related to ```Celery```. Let me know if there is anything inappropriate.

Update docs on setting send_mail_task using factory method

---

flask_security/core.py

* Changes access of roles property.  (closes #607)
--
closes #615

core: defensive access of roles property

---

flask_security/utils.py

* The decision to salt when verifying existing passwords should not
depend on the current value of SECURITY_PASSWORD_HASH, as that may
have changed since the password was stored.  (closes #272)

utils: plaintext detection of password hash

---

flask_security/translations/de_DE/LC_MESSAGES/flask_security.po

Added a German translation that avoids the Du/Sie (informal/formal) distinction.

Add German translation

---

flask_security/changeable.py
flask_security/views.py

Corrects usage user object in change_user_password so it coresponds to
its docstring.  (closes #473)

Fix type of user attribute in change_user_password

---

flask_security/datastore.py
tests/test_datastore.py

Prevents wildcard matches supported ilike

Do exact case insensitive match when looking up user

---

docs/configuration.rst
flask_security/core.py

core: respect MAIL_DEFAULT_SENDER

---

flask_security/forms.py

Adds missing translation of form labels.  (closes #628)

i18n: translate form labels

---

flask_security/datastore.py

Changes places where sqlalchemy and peewee functions are imported.
(closes #643)

Fix global imports of sqlachemy and peewee

---

flask_security/core.py
tests/conftest.py
tests/test_misc.py

closes https://github.com/inveniosoftware/flask-security-fork/issues/39

i18n: falback when babel is missing

---

flask_security/core.py
flask_security/views.py
setup.py

Remove deprecated request.json

---

.travis.yml
CHANGES
docs/conf.py
flask_security/__init__.py
flask_security/views.py
setup.py
tests/test_confirmable.py

Release v3.0.0

---

.gitignore
flask_security/templates/security/base.html
flask_security/templates/security/change_password.html
flask_security/templates/security/forgot_password.html
flask_security/templates/security/login_user.html
flask_security/templates/security/register_user.html
flask_security/templates/security/reset_password.html
flask_security/templates/security/send_confirmation.html
flask_security/templates/security/send_login.html

Created ``security/base.html`` (Used edited version of [Flask-Bootstrap/base.html](https://github.com/mbr/flask-bootstrap/blob/master/flask_bootstrap/templates/bootstrap/base.html))
All security templates now extend ``security/base.html``

Add base template to security templates

---

flask_security/views.py
tests/conftest.py
tests/test_confirmable.py
tests/test_recoverable.py

Fix for #662: removes automatic login on confirmation.

#662 Remove automatic login on email confirmation.
